//Copyright 2013 James Frasche. All rights reserved.
//Use of this code is governed by a BSD-License found in the LICENSE file.

package main

import "text/template"

var tmplraw = `<!--
// {{ .GeneratedCodeComment }}
-->
# {{.Name}}{{/*
*/}}{{if .Library}} [![GoDoc](https://godoc.org/{{.Import}}?status.svg)](https://godoc.org/{{.Import}}){{end}}{{/*
*/}}{{if .Travis}} [![Build Status](https://travis-ci.org/{{.RepoPath}}.png?branch=master)](https://travis-ci.org/{{.RepoPath}}){{end}}
{{.Synopsis}}

Download:
` + "```" + `shell
go get {{.Import}}
` + "```" + `
{{if .Command}}
If you do not have the go command on your system, you need to [Install Go](http://golang.org/doc/install) first
{{end}}
* * *
{{.Doc}}
{{if .Bugs}}
# Bugs
{{range .Bugs}}* {{.}}{{end}}
{{end}}
* * *
Automatically generated by [autoreadme](https://github.com/jimmyfrasche/autoreadme) on {{.Today}}
`
var tmpl = template.Must(template.New("").Parse(tmplraw))
