//Copyright 2013 James Frasche. All rights reserved.
//Use of this code is governed by a BSD-License found in the LICENSE file.

package main

import "text/template"

var tmplraw = `#{{.Name}}{{/*
*/}}{{if .Library}} [![GoDoc](https://godoc.org/{{.Import}}?status.png)](https://godoc.org/{{.Import}}){{end}}{{/*
*/}}{{if .Travis}} [![Build Status](https://travis-ci.org/{{.RepoPath}}.png?branch=master)](https://travis-ci.org/{{.RepoPath}}){{end}}
{{.Synopsis}}

Download:
` + "```" + `shell
go get {{.Import}}
` + "```" + `
{{if .Command}}
If you do not have the go command on your system, you need to Install Go first:
- [Binary installers and packages](https://code.google.com/p/go/downloads/list)
- [Build from source and system requirements](http://golang.org/doc/install)
{{end}}
* * *
{{.Doc}}
{{if .Bugs}}
#Bugs
{{range .Bugs}}* {{.}}{{end}}
{{end}}
* * *
Automatically generated by [autoreadme](https://github.com/jimmyfrasche/autoreadme) on {{.Today}}
`
var tmpl = template.Must(template.New("").Parse(tmplraw))
